version: "3"
services:
  vernemq:
    image: erlio/docker-vernemq
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=${DOCKER_VERNEMQ_ALLOW_ANONYMOUS}
    ports:
      # Default MQTT port
      - "1883:1883"
    # volumes:
    #   - vernemq/vernemq.confg:/etc/vernemq/vernemq.conf:ro
  
  influxdb:
    image: influxdb:latest
    environment:
        - INFLUX_DB=db0
        - INFXLUDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        - INFLUXDB_USER=${INFLUXDB_USER_TELEGRAF}
        - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD_TELEGRAF}
    volumes:
      - influxdb-storage:/var/lib/influxdb
      # Mount for influxdb configuration
      # - ./influxdb/config/:/etc/influxdb/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      # - "8083:8083"
      # UDP Port
      # - "8089:8089/udp"

  telegraf:
    image: telegraf:latest
    # environment:
    #   HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vernemq
      - influxdb

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:

  # telegraf:
  #   image: telegraf:1.11-alpine
  #   environment:
  #     HOSTNAME: "telegraf-getting-started"
  #   # Telegraf requires network access to InfluxDB
  #   links:
  #     - influxdb
  #   volumes:
  #     # Mount for telegraf configuration
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #     # Mount for Docker API access
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - vernemq
  #     - influxdb
  #
  # kapacitor:
  #   image: kapacitor:1.5-alpine
  #   volumes:
  #     # Mount for kapacitor data directory
  #     - ./kapacitor/data/:/var/lib/kapacitor
  #     # Mount for kapacitor configuration
  #     - ./kapacitor/config/:/etc/kapacitor/
  #   # Kapacitor requires network access to Influxdb
  #   links:
  #     - influxdb
  #   ports:
  #     # The API for Kapacitor is served on port 9092
  #     - "9092:9092"
  #
  # chronograf:
  #   image: chronograf:1.7-alpine
  #   environment:
  #     RESOURCES_PATH: "/usr/share/chronograf/resources"
  #   volumes:
  #     # Mount for chronograf database
  #     - ./chronograf/data/:/var/lib/chronograf/
  #   links:
  #     # Chronograf requires network access to InfluxDB and Kapacitor
  #     - influxdb
  #     - kapacitor
  #   ports:
  #     # The WebUI for Chronograf is served on port 8888
  #     - "8888:8888"
  #   depends_on:
  #     - kapacitor
  #     - influxdb
  #     - telegraf
