version: "3"
services:
  vernemq:
    image: erlio/docker-vernemq
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=${DOCKER_VERNEMQ_ALLOW_ANONYMOUS}
    ports:
      # Default MQTT port
      - "1883:1883"
    # volumes:
    #   - vernemq/vernemq.confg:/etc/vernemq/vernemq.conf:ro
  
  influxdb:
    image: influxdb:latest
    environment:
        - INFLUX_DB=db0
        - INFXLUDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        - INFLUXDB_USER=${INFLUXDB_USER_TELEGRAF}
        - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD_TELEGRAF}
    volumes:
      - influxdb-storage:/var/lib/influxdb
      # Mount for influxdb configuration
      # - ./influxdb/config/:/etc/influxdb/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      # - "8083:8083"
      # UDP Port
      # - "8089:8089/udp"

  telegraf:
    image: telegraf:latest
    # environment:
    #   HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vernemq
      - influxdb

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
